project:
  type: website

ipynb-filters: 
  - quarto_filter.py

execute:
  eval: false

website:
  title: "Ø¹Ø¨Ø¯ Ø§Ù„ÙƒØ±ÙŠÙ… Ø§Ù„Ø®Ø·ÙŠØ¨ - Abdelkareem Elkhateb | AI Researcher & Arabic NLP Specialist"
  image: quarto.png
  page-footer:
    center:
      - icon: github
        href: https://github.com/abdelkareemkobo
        aria-label: "GitHub Profile"
      - icon: cloud
        href: https://soundcloud.com/abdelkareem-elkhateb
        aria-label: "SoundCloud"
      - icon: google
        href: https://kareemai.com/kareem01095134688@gmail.com
        aria-label: "Email Contact"
      - icon: bank
        href: https://www.upwork.com/freelancers/~016a9fea792423bb9a
        aria-label: "Upwork Profile"
      - icon: rss
        href: index.xml
        aria-label: "RSS Feed"
  favicon: favicon.ico
  open-graph: 
    locale: en_US
    site-name: "Abdelkareem Elkhateb"
    image: kareem.jpg
    image-width: 1200
    image-height: 630
  google-analytics: "G-XFPC3M9TMG"
  twitter-card:
     creator: "@AbdelkareemElk1"
     card-style: summary_large_image
     image: kareem.jpg
  site-url: "https://kareemai.com/"
  description: "Kareem Elkhateb personal site, a blog about machine learning, deep learning, Web development with Astro.js, FastAPI, also Arabic Natural Language Processing and Rust language."
  repo-url: https://github.com/abdelkareemkobo/kareem_site
  # repo-actions: [edit]
  repo-branch: master
  navbar:
    title: false
    background: light
    pinned: true
    collapse: true
    collapse-below: lg
    left:
    - text: "ğŸ  Home"
      href: index.qmd
    - text: "ğŸ“® Blog"
      href: blog/feed.qmd
    - text: "ğŸ’­ TILs"
      file: til/index.qmd
    - text: "ğŸ“š Papers"
      file: papers.qmd
    - text: "ğŸ“– Books"
      file: publish.qmd
    right:
      - text: "ğŸ¥ Videos"
        href: https://youtube.com/@AbdelkareemElkhatib
      - text: "ğŸ’¼ Hire Me"
        href: https://www.upwork.com/freelancers/~016a9fea792423bb9a
      - text: "ğŸ’» GPUVec"
        href: https://gpuvec.com
      - icon: rss
        href: index.xml
        aria-label: "Blog RSS Feed"
      - icon: rss
        href: til/index.xml
        aria-label: "TILs RSS Feed"

  sidebar:
    - title: TILs
      pinned: true
      collapse-level: 1
      style: docked
      contents: notes/**
format:
  html:
    filters:
      - _extensions/jsonld/jsonld.lua
    reference-location: document
    theme:
      light: spacelab
      dark: cyborg
    toc: true
    toc-location: right
    toc-depth: 3
    toc-title: "Contents"
    syntax-definitions: 
    - fomo.xml
    fontsize: 18px
    css: 
      - styles.css
    comments:
      giscus:
        repo: abdelkareemkobo/kareem_site
        repo-id: R_kgDOQxY8kw
        category: Comments
        category-id: DIC_kwDOQxY8k84C0aRf
        mapping: pathname
        reactions-enabled: true
        theme: preferred_color_scheme
        language: en



